# Generated by Django 5.1.2 on 2024-10-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="added_at",
        ),
        migrations.RemoveField(
            model_name="topartist",
            name="added_at",
        ),
        migrations.RemoveField(
            model_name="topsong",
            name="added_at",
        ),
        migrations.AlterField(
            model_name="genre",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.user"
            ),
        ),
        migrations.AlterField(
            model_name="topartist",
            name="artist_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="topartist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.user"
            ),
        ),
        migrations.AlterField(
            model_name="topsong",
            name="song_id",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="topsong",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.user"
            ),
        ),
    ]
