# Generated by Django 5.1.2 on 2024-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0002_remove_genre_added_at_remove_topartist_added_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
