# Generated by Django 5.1.2 on 2024-10-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0003_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="genres",
                to="application.user",
            ),
        ),
        migrations.AlterField(
            model_name="topartist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top_artists",
                to="application.user",
            ),
        ),
        migrations.AlterField(
            model_name="topsong",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="top_songs",
                to="application.user",
            ),
        ),
    ]
