# Generated by Django 5.1.2 on 2024-10-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0004_alter_genre_user_alter_topartist_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_data_fetch",
            field=models.DateField(blank=True, null=True),
        ),
    ]
