# Generated by Django 5.1.2 on 2024-10-31 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0005_user_last_data_fetch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topartist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="topsong",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_data_fetch",
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="Genre12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genres_12",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genres_4",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genres_6",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopArtist12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("genres", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_artists_12",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopArtist4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("genres", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_artists_4",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopArtist6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("genres", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_artists_6",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopSong12",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_songs_12",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopSong4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_songs_4",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopSong6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_songs_6",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wrapped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "genres_6",
                    models.ManyToManyField(blank=True, to="application.genre6"),
                ),
                (
                    "top_artists_6",
                    models.ManyToManyField(blank=True, to="application.topartist6"),
                ),
                (
                    "top_songs_6",
                    models.ManyToManyField(blank=True, to="application.topsong6"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrapped",
                        to="application.user",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="TopArtist",
        ),
        migrations.DeleteModel(
            name="TopSong",
        ),
    ]
