# Generated by Django 5.1.2 on 2024-10-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0006_remove_topartist_user_remove_topsong_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wrapped",
            name="genres_6",
            field=models.ManyToManyField(
                related_name="wrapped_genres", to="application.genre6"
            ),
        ),
        migrations.AlterField(
            model_name="wrapped",
            name="top_artists_6",
            field=models.ManyToManyField(
                related_name="wrapped_artists", to="application.topartist6"
            ),
        ),
        migrations.AlterField(
            model_name="wrapped",
            name="top_songs_6",
            field=models.ManyToManyField(
                related_name="wrapped_songs", to="application.topsong6"
            ),
        ),
    ]
