# Generated by Django 5.1.2 on 2024-10-31 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "application",
            "0007_alter_wrapped_genres_6_alter_wrapped_top_artists_6_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="genre6",
            options={
                "verbose_name": "Top Genre",
                "verbose_name_plural": "Top Genres for Last 6 Months",
            },
        ),
        migrations.AlterModelOptions(
            name="topartist6",
            options={
                "verbose_name": "Top Artist",
                "verbose_name_plural": "Top Artists for Last 6 Months",
            },
        ),
        migrations.AlterModelOptions(
            name="topsong6",
            options={
                "verbose_name": "Top Song",
                "verbose_name_plural": "Top Songs for Last 6 Months",
            },
        ),
    ]
