# Generated by Django 5.1.2 on 2024-10-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0008_alter_genre6_options_alter_topartist6_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrapped",
            name="spotify_id",
            field=models.CharField(
                default="default_spotify_id", max_length=255, unique=True
            ),
        ),
    ]
