# Generated by Django 5.1.2 on 2024-11-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0009_wrapped_spotify_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wrapped",
            name="spotify_id",
            field=models.CharField(max_length=255),
        ),
    ]
