# Generated by Django 5.1 on 2024-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0010_alter_wrapped_spotify_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wrapped",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
