# Generated by Django 5.1.3 on 2024-11-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0011_alter_wrapped_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="topsong6",
            name="album_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
