# Generated by Django 5.1.2 on 2024-11-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0012_topsong6_album_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrapped",
            name="top_artists_12",
            field=models.ManyToManyField(
                related_name="wrapped_artists", to="application.topartist12"
            ),
        ),
        migrations.AddField(
            model_name="wrapped",
            name="top_artists_4",
            field=models.ManyToManyField(
                related_name="wrapped_artists", to="application.topartist4"
            ),
        ),
        migrations.AddField(
            model_name="wrapped",
            name="top_songs_12",
            field=models.ManyToManyField(
                related_name="wrapped_songs", to="application.topsong12"
            ),
        ),
        migrations.AddField(
            model_name="wrapped",
            name="top_songs_4",
            field=models.ManyToManyField(
                related_name="wrapped_songs", to="application.topsong4"
            ),
        ),
    ]
