# Generated by Django 5.1.2 on 2024-11-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0013_wrapped_top_artists_12_wrapped_top_artists_4_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrapped",
            name="ghosted_artists",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wrapped",
            name="recent_tracks",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wrapped",
            name="rising_artists",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="wrapped",
            name="top_unfollowed_artists",
            field=models.JSONField(default=list),
        ),
    ]
