# Generated by Django 5.1 on 2024-11-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0016_alter_user_username_alter_wrapped_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopArtist6",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("genres", models.JSONField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_artists_6",
                        to="application.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top Artist",
                "verbose_name_plural": "Top Artists for Last 6 Months",
            },
        ),
    ]
